name: Steps-Types
on:  
    workflow_dispatch:
jobs:
  job-1:
      runs-on: ubuntu-24.04
      steps:
        - name: Testing-bash-shell
          run: echo "Hello From Shell"
  job-2:
     runs-on: ubuntu-24.04
     steps:
         - name: Testing-pytho-shell
           run: print("Hello From Python!!")
           shell: python
  job-3:
      runs-on: ubuntu-22.04
      steps: 
          - name: Testing-javascript-action
            uses: actions/hello-world-javascript-action@v1
            with:
              who-to-greet: "Mayur"
     
